### ISSUE TITLE
Improvement: Try resuming file after ConnectionResetError

### ISSUE THREAD

**Issue by mmterpstra** [genomescan/gsport#2]
I'm using gsport version 1.6.1 installation for dowloading files from Genomescan. 

During download however the connection botches and give the ConnectionResetError. I'd suggest to either try and resume/retry downloading the file after waiting a few seconds or retry at the end of the download.

Other features I would like you to consider:
 - An option to do an md5 checksum.
 - log friendly processing or at least make it so that the logging only happens after start/30 secs.
 - making it so that the gsport program actually exits after downloading 

Error (including the excessive loggin of the progress bar):

```
Traceback (most recent call last):B 96.8 MB/sec ETA: 2m     
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer  
 73% Downloading 45.7 GB of 62.9 GB 96.8 MB/sec ETA: 2m     
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):B 96.8 MB/sec ETA: 2m     
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/software/software/Python/3.6.4-foss-2018a/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/gsport.py", line 223, in download_file
    with requests.get(url, stream=True, cookies=self.cookies) as r:
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/data/umcg-mterpstra/apps/software/gsport/1.6.1-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by tomkuipers1402** [comment]
I've got the same problem here as well (python v3.9.1, gsport v1.6.2)

**Comment by tomkuipers1402** [comment]
I fixed it by adding a thread flag to my command (-t). The thread option only works on Linux though...

**Comment by gerbenvoshol** [comment]
Closing as recent improvements have been made to error handling and download resumption. If you feel a specific scenario is still not covered, feel free to open a new issue.
